# Generated by Django 3.0.3 on 2020-03-12 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0002_auto_20200312_1000'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tweet',
            name='username',
        ),
    ]
