# Generated by Django 3.0.3 on 2020-04-22 18:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitterapp', '0006_auto_20200422_1125'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='user',
            new_name='tweetuser',
        ),
    ]
